// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/fusic/skill-api/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// LoanRepository is an autogenerated mock type for the LoanRepository type
type LoanRepository struct {
	mock.Mock
}

// ApplyLoan provides a mock function with given fields: application
func (_m *LoanRepository) ApplyLoan(application models.LoanApplication) error {
	ret := _m.Called(application)

	if len(ret) == 0 {
		panic("no return value specified for ApplyLoan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.LoanApplication) error); ok {
		r0 = rf(application)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllLoans provides a mock function with given fields: queryModel
func (_m *LoanRepository) GetAllLoans(queryModel models.ListLoansQuery) ([]models.LoanApplication, int64, error) {
	ret := _m.Called(queryModel)

	if len(ret) == 0 {
		panic("no return value specified for GetAllLoans")
	}

	var r0 []models.LoanApplication
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(models.ListLoansQuery) ([]models.LoanApplication, int64, error)); ok {
		return rf(queryModel)
	}
	if rf, ok := ret.Get(0).(func(models.ListLoansQuery) []models.LoanApplication); ok {
		r0 = rf(queryModel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LoanApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(models.ListLoansQuery) int64); ok {
		r1 = rf(queryModel)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(models.ListLoansQuery) error); ok {
		r2 = rf(queryModel)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetLoanStatus provides a mock function with given fields: applicationId
func (_m *LoanRepository) GetLoanStatus(applicationId string) (models.LoanApplication, error) {
	ret := _m.Called(applicationId)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanStatus")
	}

	var r0 models.LoanApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.LoanApplication, error)); ok {
		return rf(applicationId)
	}
	if rf, ok := ret.Get(0).(func(string) models.LoanApplication); ok {
		r0 = rf(applicationId)
	} else {
		r0 = ret.Get(0).(models.LoanApplication)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(applicationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoanRepository creates a new instance of LoanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanRepository {
	mock := &LoanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
