// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/fusic/skill-api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// LoanService is an autogenerated mock type for the LoanService type
type LoanService struct {
	mock.Mock
}

// ApplyLoan provides a mock function with given fields: request
func (_m *LoanService) ApplyLoan(request entity.ApplyLoanRequest) (entity.ApplyLoanResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ApplyLoan")
	}

	var r0 entity.ApplyLoanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.ApplyLoanRequest) (entity.ApplyLoanResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(entity.ApplyLoanRequest) entity.ApplyLoanResponse); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(entity.ApplyLoanResponse)
	}

	if rf, ok := ret.Get(1).(func(entity.ApplyLoanRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllLoans provides a mock function with given fields: query
func (_m *LoanService) GetAllLoans(query entity.ListLoansQuery) (entity.ListLoansResponse, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllLoans")
	}

	var r0 entity.ListLoansResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.ListLoansQuery) (entity.ListLoansResponse, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(entity.ListLoansQuery) entity.ListLoansResponse); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Get(0).(entity.ListLoansResponse)
	}

	if rf, ok := ret.Get(1).(func(entity.ListLoansQuery) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoanStatus provides a mock function with given fields: applicationId
func (_m *LoanService) GetLoanStatus(applicationId string) (entity.LoanApplication, error) {
	ret := _m.Called(applicationId)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanStatus")
	}

	var r0 entity.LoanApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entity.LoanApplication, error)); ok {
		return rf(applicationId)
	}
	if rf, ok := ret.Get(0).(func(string) entity.LoanApplication); ok {
		r0 = rf(applicationId)
	} else {
		r0 = ret.Get(0).(entity.LoanApplication)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(applicationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoanService creates a new instance of LoanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanService {
	mock := &LoanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
