services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    volumes:
      - mysql_data:/var/lib/mysql
    # networks:
    #   - my-network
    restart: unless-stopped

# ----------------------------
# NETWORK
# ----------------------------
# networks:
#   my-network:
#     external: true

# ----------------------------
# VOLUMES
# ----------------------------
volumes:
  mysql_data:
    external: true
